name: Test and Release

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test-2_5_8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Install dependencies
      run: bundle install
    - name: Run linter
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
